version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_linux_amd64.zip
      - unzip terraform_0.14.4_linux_amd64.zip
      - mv terraform /usr/local/bin
      - rm terraform_0.14.4_linux_amd64.zip
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
     # - terraform init
      - terraform plan
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
